"""Reused equipment data. Total: orig 7,672.09万元, net 2,675.56万元, install 415.28万元."""


def get_reuse_equipment() -> list[dict]:
    """Return a list of reused equipment items."""
    return [
        {
            "name": "液压支架",
            "model": "ZY6800-20/40",
            "quantity": 120,
            "original_value": 3393.73,
            "net_value": 169.69,
            "install_fee": 142.54,
        },
        {
            "name": "采煤机",
            "model": "MG-300/730QWD1",
            "quantity": 1,
            "original_value": 354.16,
            "net_value": 306.50,
            "install_fee": 14.87,
        },
        {
            "name": "运输机",
            "model": "SGZ-800/800(1500t/h)",
            "quantity": 1,
            "original_value": 911.50,
            "net_value": 442.46,
            "install_fee": 91.15,
        },
        {
            "name": "转载机",
            "model": "SZZ-800/315(1800t/h)",
            "quantity": 1,
            "original_value": 357.76,
            "net_value": 139.67,
            "install_fee": 15.03,
        },
        {
            "name": "悬臂式掘进机",
            "model": "EBZ260Q",
            "quantity": 1,
            "original_value": 497.35,
            "net_value": 383.16,
            "install_fee": 20.89,
        },
        {
            "name": "悬臂式掘进机",
            "model": "EBZ260Q",
            "quantity": 1,
            "original_value": 460.18,
            "net_value": 318.10,
            "install_fee": 19.33,
        },
        {
            "name": "凿井提升机",
            "model": "2JKZ-4*2.65/15",
            "quantity": 1,
            "original_value": 540.00,
            "net_value": 324.00,
            "install_fee": 0,
        },
        {
            "name": "凿井提升机",
            "model": "2JKZ-4*2.65/15",
            "quantity": 1,
            "original_value": 540.00,
            "net_value": 324.00,
            "install_fee": 56.70,
        },
        {
            "name": "乳化液泵",
            "model": "BRW400/37.5",
            "quantity": 1,
            "original_value": 43.97,
            "net_value": 17.16,
            "install_fee": 1.85,
        },
        {
            "name": "乳化液泵",
            "model": "BRW400/37.5",
            "quantity": 1,
            "original_value": 31.89,
            "net_value": 11.50,
            "install_fee": 1.34,
        },
        {
            "name": "干式变压器",
            "model": "KBSG630型",
            "quantity": 3,
            "original_value": 12.62,
            "net_value": 7.57,
            "install_fee": 1.27,
        },
        {
            "name": "干式变压器",
            "model": "KBSG500型",
            "quantity": 5,
            "original_value": 11.26,
            "net_value": 6.76,
            "install_fee": 1.14,
        },
        {
            "name": "干式变压器",
            "model": "KBSG315型",
            "quantity": 7,
            "original_value": 10.688,
            "net_value": 6.41,
            "install_fee": 1.08,
        },
        {
            "name": "矿用隔爆型真空电磁起动器",
            "model": "QBZ-120/660(380)",
            "quantity": 20,
            "original_value": 17.2,
            "net_value": 10.32,
            "install_fee": 1.72,
        },
        {
            "name": "矿用隔爆型真空电磁起动器",
            "model": "QBZ-120/1140(660)",
            "quantity": 59,
            "original_value": 50.74,
            "net_value": 30.44,
            "install_fee": 5.07,
        },
        {
            "name": "矿用隔爆型真空电磁起动器",
            "model": "QBZ-200/1140(660)",
            "quantity": 9,
            "original_value": 9.45,
            "net_value": 5.67,
            "install_fee": 0.94,
        },
        {
            "name": "油侵变压器",
            "model": "S11-M-1000/6型",
            "quantity": 2,
            "original_value": 1.07,
            "net_value": 0.64,
            "install_fee": 0.11,
        },
        {
            "name": "矿用隔爆型风机开关",
            "model": "QBZ-120(660/1140)F",
            "quantity": 10,
            "original_value": 16.39,
            "net_value": 9.83,
            "install_fee": 1.64,
        },
        {
            "name": "矿用隔爆可逆起动器",
            "model": "QBZ-120(660/1140)N",
            "quantity": 20,
            "original_value": 25.26,
            "net_value": 15.16,
            "install_fee": 2.53,
        },
        {
            "name": "破碎机",
            "model": "PLM-2200",
            "quantity": 1,
            "original_value": 44.83,
            "net_value": 17.50,
            "install_fee": 1.88,
        },
        {
            "name": "矿用隔爆兼本质安全型多回路真空电磁起动器",
            "model": "QJZ-630/1140(660)-4",
            "quantity": 1,
            "original_value": 17.95,
            "net_value": 5.19,
            "install_fee": 1.79,
        },
        {
            "name": "矿用隔爆兼本质安全型多回路真空电磁起动器",
            "model": "QJZ-630/1140(660)-4",
            "quantity": 1,
            "original_value": 17.95,
            "net_value": 5.19,
            "install_fee": 1.79,
        },
        {
            "name": "矿用隔爆兼本质安全型多回路真空电磁起动器",
            "model": "QJZ-630/1140(660)-4",
            "quantity": 1,
            "original_value": 16.81,
            "net_value": 6.43,
            "install_fee": 1.68,
        },
        {
            "name": "矿用隔爆型移动变电站",
            "model": "KBSGZY-1250/6",
            "quantity": 1,
            "original_value": 17.95,
            "net_value": 5.30,
            "install_fee": 1.79,
        },
        {
            "name": "矿用隔爆型移动变电站",
            "model": "KBSGZY-1250/6",
            "quantity": 1,
            "original_value": 24.14,
            "net_value": 9.45,
            "install_fee": 2.41,
        },
        {
            "name": "矿用隔爆型移动变电站",
            "model": "KBSGZY-1250/6",
            "quantity": 1,
            "original_value": 24.14,
            "net_value": 9.45,
            "install_fee": 2.41,
        },
        {
            "name": "矿用隔爆型移动变电站",
            "model": "KBSGZY-1600/6/3.45",
            "quantity": 1,
            "original_value": 22.31,
            "net_value": 6.59,
            "install_fee": 2.23,
        },
        {
            "name": "矿用隔爆型移动变电站",
            "model": "KBSGZY-2000/6/3.45",
            "quantity": 1,
            "original_value": 30.60,
            "net_value": 11.95,
            "install_fee": 3.06,
        },
        {
            "name": "矿用隔爆型移动变电站",
            "model": "KBSGZY-2000/6/3.45",
            "quantity": 1,
            "original_value": 30.60,
            "net_value": 11.95,
            "install_fee": 3.06,
        },
        {
            "name": "矿用隔爆兼本质安全型多回路高压真空电磁起动器",
            "model": "QJGZ1-2000/3300-8",
            "quantity": 1,
            "original_value": 39.25,
            "net_value": 22.78,
            "install_fee": 3.92,
        },
        {
            "name": "矿用隔爆兼本质安全型多回路高压真空电磁起动器",
            "model": "QJGZ1-2000/3300-8",
            "quantity": 1,
            "original_value": 38.30,
            "net_value": 16.42,
            "install_fee": 3.83,
        },
        {
            "name": "矿用隔爆兼本质安全型多回路高压真空电磁起动器",
            "model": "QJGZ1-2000/3300-8",
            "quantity": 1,
            "original_value": 62.05,
            "net_value": 18.33,
            "install_fee": 6.21,
        },
    ]
